name: bertopicnew
dependencies:
  - ipykernel
  - pip
  - python=3.9.19
  - pip:
      - bertopic==0.16.2
      - hdbscan==0.8.36
      - keybert==0.8.4
      - matplotlib==3.8.0
      - nbformat==5.10.4
      - nltk==3.8.1
      - pandas==2.0.1
      - plotly==5.22.0
      - scikit-learn==1.2.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentence-transformers==3.0.1
      - spacy==3.7.5
      - spacy_download
      - umap-learn==0.5.6